### ISSUE TITLE
How to retrieve the final context vector from the encoder?

### ISSUE THREAD

**Issue by shahbazsyed** [eladhoffer/seq2seq.pytorch#4]
Hi,
I want to encode a small document into a vector using the RNN encoder. Can you kindly tell me how to get the final context vector representation of a document?

**Comment by alphadl** [comment]
Hi~ hoping I can help you~
Taking `seq2seq.pytorch/seq2seq/models/seq2seq_base.py` for example,  you just need to get the following variable 
[context](https://github.com/eladhoffer/seq2seq.pytorch/blob/master/seq2seq/models/seq2seq_base.py#L49)
