### ISSUE TITLE
Translate_English_German_LSTM.ipynb in the examples dir seems to be broken

### ISSUE THREAD

**Issue by yucongo** [eladhoffer/seq2seq.pytorch#6]
Can't open the file in the Chrome browser. Jupyter Notebook Preview in  VS Code gives: SyntaxError: Unexpected string in JSON at position 239.

Would appreciate it if this could be fixed. Thanks a lot.

**Comment by yucongo** [comment]
I found the culprit: somehow the "," at the end of line 12 is missing.

Fix: add a "," at the end of line 12.

**Comment by eladhoffer** [comment]
fixed, thanks.
